version: 5.1.0
variant: default
logo:
    text: Chendongtian's Blog
head:
    favicon: /images/favicon.ico
    manifest:
        name: 
        short_name: 
        start_url: 
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        Tech: /categories/tech
        HIT: /categories/HIT
        Music: /categories/music
        Citations: /categories/citations
        Misc: /categories/misc
        About: /about
    links:
        Source for this blog:
            icon: fab fa-github
            url: https://github.com/CDT/blog
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/ppoffice/hexo-theme-icarus
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
comment:
    type: disqus
    shortname: personal-blog-wx403pf6sj
donates:
    -
        type: afdian
        url: https://afdian.net/@chendongtian/plan
    -
        type: alipay
        qrcode: /images/alipay_shouqian.jpg
    -
        type: wechat
        qrcode: /images/qq_shouqian.jpg
share:
    type: sharethis
    install_url: https://platform-api.sharethis.com/js/sharethis.js#property=62e33f2e987470001990b838&product=sop
sidebar:
    left:
        sticky: true
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: Chendongtian
        author_title: Waste the life in a desired manner
        location: Wuhan, China
        avatar: /images/favicon.ico
        avatar_rounded: false
        gravatar: 
        follow_link: https://github.com/CDT
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/CDT
            Linkedin:
                icon: fab fa-linkedin
                url: https://www.linkedin.cn/incareer/in/%E6%B4%9E%E5%A4%A9-%E9%99%88-214711242
            Stackoverflow:
                icon: fab fa-stack-overflow
                url: https://stackoverflow.com/users/1553886/cdt
    -
        position: left
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        position: left
        type: links
        links:
            Reorx's Forge(Close Friend): http://reorx.com/
            James Cai(Junior school deskmate): https://hcai.me
    -
        position: left
        type: categories
    -
        position: left
        type: recent_posts
    -
        position: left
        type: archives
    -
        position: left
        type: tags
        order_by: name
        amount: 
        show_count: true
    -
        position: right
        type: adsense
        client_id: ca-pub-2110925248434778
        slot_id: xxxxxxx
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    bing_webmaster:
        tracking_id: 
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: 
    hotjar:
        site_id: 
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
